SVCCTempleApplicationNew/SVCCTempleWeb/Models/CalendarData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SVCCTempleWeb.Models
{
    public class CalendarData
    {
        public DateTime StartDate { set; get; }
        public string StartTime { set; get; }
        public DateTime FinishDate { set; get; }
        public string FinishTime { set; get; }
        public long CodeTypeNameId { set; get; }
        public string CodeTypeNameDesc { set; get; }
        public string CodeTypeDesc { set; get; }
        public string CodeTypeDesc1 { set; get; }
        public long CalendarCodeId { set; get; }
        public long CodeDataNameId { set; get; }
        public string CodeDataNameDesc { set; get; }
        public string CodeDataDesc0 { set; get; }
        public string CodeDataDesc9 { set; get; }
        public string Color { set; get; }
        public string LocationNameDesc { set; get; }
    }
}

SVCCTempleApplicationNew/SVCCTempleWeb/Models/CalendarDataViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SVCCTempleWeb.Models
{
    public class CalendarDataViewModel
    {
        public long CalendarYear { set; get; }
        public string FinishDate { set; get; }
        public List<CalendarDateDataModel> NakshatraDataModels { set; get; }
        public List<CalendarDateDataModel> RasiDataModels { set; get; }
        public List<RiseSetModel> RiseSetModels { set; get; }
        public string StartDate { set; get; }
        public TempleScheduleMasterList TempleScheduleMasterList { set; get; }
        public TempleScheduleUploadList TempleScheduleUploadList { set; get; }
        public TempleScheduleUploadList TempleFestivalUploadList { set; get; }
        public List<CalendarDateDataModel> ThithiDataModels { set; get; }
        public ResponseObjectModel0 ResponseObjectModel { set; get; }
    }
}

SVCCTempleApplicationNew/SVCCTempleWeb/Models/TempleScheduleMasterList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SVCCTempleWeb.Models
{
    public class TempleScheduleMasterList
    {
        public List<TempleScheduleMasterModel> TempleScheduleMasterModels { set; get; }
        public ResponseObjectModel0 ResponseObjectModel { set; get; }
    }
}

SVCCTempleApplicationNew/SVCCTempleWeb/Models/TempleScheduleUploadList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SVCCTempleWeb.Models
{
    public class TempleScheduleUploadList
    {
        public List<TempleScheduleUploadModel> TempleScheduleUploadModels { set; get; }
        public ResponseObjectModel0 ResponseObjectModel { set; get; }
    }
}

SVCCTempleApplicationNew/SVCCTempleWeb/Controllers/SVCCTempleFremontController.cs
using ArchitectureLibraryException;
using ArchitectureLibraryUtility;
using Newtonsoft.Json;
using SVCCTempleWeb.ClassCode;
using SVCCTempleWeb.Enumerations;
using SVCCTempleWeb.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace SVCCTempleWeb.Controllers
{
    [OutputCache(Duration = 0)]
    public class SVCCTempleFremontController : Controller
    {
        private const string LOCATION_NAME_DESC = "FREMONT";
        private const string LOCATION_NAME_DESC1 = "Fremont";
        private string execUniqueId = Utilities.CreateExecUniqueId();
        private readonly long clientId = long.Parse(Utilities.GetApplicationValue("ClientId"));

        // GET: Index
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Index(string id)
        {
            string methodName = MethodBase.GetCurrentMethod().Name, ipAddress = Utilities.GetIPAddress(), loggedInUserId = "";
            ExceptionLogger exceptionLogger = new ExceptionLogger(Utilities.GetApplicationValue("ApplicationName"), ipAddress, execUniqueId, loggedInUserId, Assembly.GetCallingAssembly().FullName, Assembly.GetExecutingAssembly().FullName, MethodBase.GetCurrentMethod().DeclaringType.ToString());//, currentMethodDeclaringType_);// MethodBase.GetCurrentMethod().DeclaringType.ToString());
            exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00000000 :: Enter");
            ViewData["ActionName"] = "Index";
            SVCCTempleBL svccTempleBL = new SVCCTempleBL();
            int.TryParse(id, out int tabIndex);
            string serverDirectoryName = Server.MapPath("~/UpcomingFestivals/" + LOCATION_NAME_DESC1 + "/");
            IndexModel indexModel = svccTempleBL.BuildIndexModel(LOCATION_NAME_DESC, LOCATION_NAME_DESC1, tabIndex, serverDirectoryName, clientId, ipAddress, loggedInUserId, execUniqueId);
            //indexModel.TabIndex = id == null ? 0 : int.Parse(id);
            exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00090000 :: Exit");
            return View(indexModel);
        }

        #region
        //// GET: Index
        //[AllowAnonymous]
        //[HttpGet]
        //public ActionResult Index9()
        //{
        //    string methodName = MethodBase.GetCurrentMethod().Name, ipAddress = Utilities.GetIPAddress(), loggedInUserId = "";
        //    ExceptionLogger exceptionLogger = new ExceptionLogger(Utilities.GetApplicationValue("ApplicationName"), ipAddress, execUniqueId, loggedInUserId, Assembly.GetCallingAssembly().FullName, Assembly.GetExecutingAssembly().FullName, MethodBase.GetCurrentMethod().DeclaringType.ToString());//, currentMethodDeclaringType_);// MethodBase.GetCurrentMethod().DeclaringType.ToString());
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00000000 :: Enter");
        //    ViewData["ActionName"] = "Index";
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00090000 :: Exit");
        //    return View();
        //}

        //// GET: SVCCTempleFremont
        //[AllowAnonymous]
        //[HttpGet]
        //public ActionResult Index7(string id)
        //{
        //    string methodName = MethodBase.GetCurrentMethod().Name, ipAddress = Utilities.GetIPAddress(), loggedInUserId = "";
        //    ExceptionLogger exceptionLogger = new ExceptionLogger(Utilities.GetApplicationValue("ApplicationName"), ipAddress, execUniqueId, loggedInUserId, Assembly.GetCallingAssembly().FullName, Assembly.GetExecutingAssembly().FullName, MethodBase.GetCurrentMethod().DeclaringType.ToString());//, currentMethodDeclaringType_);// MethodBase.GetCurrentMethod().DeclaringType.ToString());
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00000000 :: Enter");
        //    ViewData["ActionName"] = "Index";
        //    SVCCTempleBL svccTempleBL = new SVCCTempleBL();
        //    int tabIndex;
        //    try
        //    {
        //        tabIndex = id == null ? 0 : int.Parse(id);
        //    }
        //    catch
        //    {
        //        tabIndex = 0;
        //    }
        //    string serverDirectoryName = Server.MapPath("~/UpcomingFestivals/" + LOCATION_NAME_DESC1 + "/");
        //    IndexModel indexModel = svccTempleBL.BuildIndexModel(LOCATION_NAME_DESC, LOCATION_NAME_DESC1, serverDirectoryName, tabIndex, execUniqueId);
        //    //indexModel.TabIndex = id == null ? 0 : int.Parse(id);
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00090000 :: Exit");
        //    return View(indexModel);
        //}

        //[AllowAnonymous]
        //[HttpGet]
        //public ActionResult IndexGenerateTemplEventData(string fromDate, string toDate)
        //{
        //    string methodName = MethodBase.GetCurrentMethod().Name, ipAddress = Utilities.GetIPAddress(), loggedInUserId = "";
        //    ExceptionLogger exceptionLogger = new ExceptionLogger(Utilities.GetApplicationValue("ApplicationName"), ipAddress, execUniqueId, loggedInUserId, Assembly.GetCallingAssembly().FullName, Assembly.GetExecutingAssembly().FullName, MethodBase.GetCurrentMethod().DeclaringType.ToString());//, currentMethodDeclaringType_);// MethodBase.GetCurrentMethod().DeclaringType.ToString());
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00000000 :: Enter");
        //    ViewData["ActionName"] = "IndexGenerateTemplEventData";
        //    SVCCTempleBL svccTempleBL = new SVCCTempleBL();
        //    string startDate = DateTime.Parse(fromDate).ToString("yyyy-MM-dd"), finishDate = DateTime.Parse(toDate).ToString("yyyy-MM-dd");
        //    svccTempleBL.GenerateTempleEventData(LOCATION_NAME_DESC, startDate, finishDate, execUniqueId);
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00090000 :: Exit");
        //    return View();
        //}

        //[AllowAnonymous]
        //[HttpGet]
        //public ActionResult IndexGenerateTempleScheduleData(string fromDate, string toDate, string dataType)
        //{
        //    //http://localhost:21455/SVCCTempleFremont/IndexGenerateTempleScheduleData?fromDate=2025-01-01&toDate=2025-12-31&dataType=1
        //    string methodName = MethodBase.GetCurrentMethod().Name, ipAddress = Utilities.GetIPAddress(), loggedInUserId = "";
        //    ExceptionLogger exceptionLogger = new ExceptionLogger(Utilities.GetApplicationValue("ApplicationName"), ipAddress, execUniqueId, loggedInUserId, Assembly.GetCallingAssembly().FullName, Assembly.GetExecutingAssembly().FullName, MethodBase.GetCurrentMethod().DeclaringType.ToString());//, currentMethodDeclaringType_);// MethodBase.GetCurrentMethod().DeclaringType.ToString());
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00000000 :: Enter");
        //    ViewData["ActionName"] = "IndexGenerateTempleScheduleData";
        //    SVCCTempleBL svccTempleBL = new SVCCTempleBL();
        //    string startDate = DateTime.Parse(fromDate).ToString("yyyy-MM-dd"), finishDate = DateTime.Parse(toDate).ToString("yyyy-MM-dd");
        //    svccTempleBL.GenerateTempleScheduleUploadData(LOCATION_NAME_DESC, LOCATION_NAME_DESC1, startDate, finishDate, dataType, clientId, ipAddress, execUniqueId, loggedInUserId);
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00090000 :: Exit");
        //    return View();
        //}

        //[AllowAnonymous]
        //[HttpGet]
        //public ActionResult Index1()
        //{
        //    string methodName = MethodBase.GetCurrentMethod().Name, ipAddress = Utilities.GetIPAddress(), loggedInUserId = "";
        //    ExceptionLogger exceptionLogger = new ExceptionLogger(Utilities.GetApplicationValue("ApplicationName"), ipAddress, execUniqueId, loggedInUserId, Assembly.GetCallingAssembly().FullName, Assembly.GetExecutingAssembly().FullName, MethodBase.GetCurrentMethod().DeclaringType.ToString());//, currentMethodDeclaringType_);// MethodBase.GetCurrentMethod().DeclaringType.ToString());
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00000000 :: Enter");
        //    ViewData["ActionName"] = "Index";
        //    string importantIdsList = "1, 2, 3, 4, 5, 6, 7, 10, 11";
        //    exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00090000 :: Exit");
        //    SVCCTempleBL svccTempleBL = new SVCCTempleBL();
        //    Dictionary<string, List<ImportantDatesModelNew>> monthImportantDatesModels = svccTempleBL.GetImportantDates2A(LOCATION_NAME_DESC, 4, importantIdsList, "51, 52, 54, 55, 56, 61, 62, 65, 41", execUniqueId);//5001, 5002, 5005, 5006, 5007, 5008, 5009
        //    return View(monthImportantDatesModels);
        //}
        #endregion

        [AllowAnonymous]
        [HttpGet]
        public ActionResult AboutUs()
        {
            string methodName = MethodBase.GetCurrentMethod().Name, ipAddress = Utilities.GetIPAddress(), loggedInUserId = "";
            ExceptionLogger exceptionLogger = new ExceptionLogger(Utilities.GetApplicationValue("ApplicationName"), ipAddress, execUniqueId, loggedInUserId, Assembly.GetCallingAssembly().FullName, Assembly.GetExecutingAssembly().FullName, MethodBase.GetCurrentMethod().DeclaringType.ToString());//, currentMethodDeclaringType_);// MethodBase.GetCurrentMethod().DeclaringType.ToString());
            exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00000000 :: Enter");
            ViewData["ActionName"] = "AboutUs";
            exceptionLogger.LogInfo(methodName, Utilities.GetCallerLineNumber(), "00090000 :: Exit");
            return View();
        }

        [AllowAnonymous]
        [HttpGet]

SVCCTempleApplicationNew/SVCCTempleWeb/Views/SVCCTempleFremont/Calendar.cshtml
@model SVCCTempleWeb.Models.CalendarModel

@{
    ViewBag.Title = "Calendar";
    Layout = "_Layout2.cshtml";
}

<div id="divCalendar">
    @Html.Partial("_Calendar", Model)
</div>
<script type="text/javascript">
<!--
    function window_onload() {

    }
    function calendarMonth_onchange() {
        window.location.href = "@Url.Action("Calendar", "SVCCTempleFremont")" + "?id=" + document.getElementById("calendarYear").value + "-" + document.getElementById("calendarMonth").value;
    }
    function calendarYear_onchange() {
        window.location.href = "@Url.Action("Calendar", "SVCCTempleFremont")" + "?id=" + document.getElementById("calendarYear").value + "-" + document.getElementById("calendarMonth").value;
    }
    function calendarPrev_onclick() {
        if (document.getElementById("calendarMonth").selectedIndex == 0) {
            if (document.getElementById("calendarYear").selectedIndex == 0) {
                ;
            }
            else {
                document.getElementById("calendarYear").selectedIndex--;
                document.getElementById("calendarMonth").selectedIndex = document.getElementById("calendarMonth").options.length - 1;
                window.location.href = "@Url.Action("Calendar", "SVCCTempleFremont")" + "?id=" + document.getElementById("calendarYear").value + "-" + document.getElementById("calendarMonth").value;
            }
        }
        else {
            document.getElementById("calendarMonth").selectedIndex--;
            window.location.href = "@Url.Action("Calendar", "SVCCTempleFremont")" + "?id=" + document.getElementById("calendarYear").value + "-" + document.getElementById("calendarMonth").value;
        }
    }
    function calendarNext_onclick() {
        if (document.getElementById("calendarMonth").selectedIndex == document.getElementById("calendarMonth").options.length - 1) {
            if (document.getElementById("calendarYear").selectedIndex == document.getElementById("calendarYear").options.length - 1) {
                ;
            }
            else {
                document.getElementById("calendarYear").selectedIndex++;
                document.getElementById("calendarMonth").selectedIndex = 0;
                window.location.href = "@Url.Action("Calendar", "SVCCTempleFremont")" + "?id=" + document.getElementById("calendarYear").value + "-" + document.getElementById("calendarMonth").value;
            }
        }
        else {
            document.getElementById("calendarMonth").selectedIndex++;
            window.location.href = "@Url.Action("Calendar", "SVCCTempleFremont")" + "?id=" + document.getElementById("calendarYear").value + "-" + document.getElementById("calendarMonth").value;
        }
    }
    //-->
</script>

SVCCTempleApplicationNew/SVCCTempleWeb/Views/SVCCTempleFremont/RegisterUserLoginUser.cshtml
@model SVCCTempleWeb.Models.RegisterUserLoginUserModel
@{
    ViewBag.Title = "RegisterUserLoginUser";
    Layout = "_Layout3.cshtml";
}

@*<h2 class="text-center mb-4" style="color: #a54000; font-weight: bold;">
    R E G I S T E R / <span style="color: #0000ff;">C O N T A C T&nbsp;&nbsp;U S</span><br />
    <span style="color: #0000ff;">L O G I N</span> / R E S E T&nbsp;&nbsp;P A S S W O R D
</h2>*@
<div class="main">
    <div class="container">
        <div class="col-md-6">
            @Html.Partial("_RegisterUserProf", Model.RegisterUserProfModel)
            <hr style="background-color: #000000; display: block; font-size: 18px; font-weight: bold; height: 1px;" />
            @*Html.Partial("_ContactUs", Model.ContactUsModel)*@
        </div>
        <div class="col-md-6">
            @Html.Partial("_LoginUserProf", Model.LoginUserProfModel)
            <hr style="background-color: #000000; display: block; font-size: 18px; font-weight: bold; height: 1px;" />
            @Html.Partial("_ResetPassword", Model.ResetPasswordModel)
        </div>
    </div>
</div>

<script type="text/javascript">
    function window_onload() {
    }
</script>

SVCCTempleApplicationNew/SVCCTempleWeb/Views/SVCCTempleFremont/SankalpamInfo.cshtml
@model SVCCTempleWeb.Models.SankalpamInfoModel
@{
    ViewBag.Title = "Sponsorship";
    //Layout = "_Layout2.cshtml";
}
<h2 style="font-weight: bold;">Sankalpam Info</h2>
@Html.Partial("_SankalpamInfo", Model)
<script type="text/javascript">
    function window_onload() {
    }
</script>

SVCCTempleApplicationNew/SVCCTempleWeb/Views/SVCCTempleFremont/UpdatePassword.cshtml
@model SVCCTempleWeb.Models.UpdatePasswordModel
@{
    ViewBag.Title = "UpdatePassword";
    Layout = "_Layout2.cshtml";
}
<div class="container">
    <div class="col-md-12">
        @Html.Partial("_UpdatePassword", Model)
    </div>
</div>
<script type="text/javascript">
    function window_onload() {

    }
</script>

SVCCTempleApplicationNew/SVCCTempleWeb/Views/SVCCTempleFremont/_DonationReport.cshtml
@model SVCCTempleWeb.Models.DonationReportModel
<h3 style="color: #a54000; font-size: 36px; font-weight: bold; letter-spacing: 7px; text-transform: uppercase;">Donation Report</h3>
<img src="~/Images/UnderConstruction.jpg" />

SVCCTempleApplicationNew/SVCCTempleWeb/Views/SVCCTempleFremont/_Layout5.cshtml
@{ 
    string templeFullName = @ApplicationInstance.Application["FremontTempleFullName"].ToString();
    string templeName = @ApplicationInstance.Application["FremontTempleName"].ToString();
    string telephoneNum1 = long.Parse(ApplicationInstance.Application["FremontTemplePhone1"].ToString()).ToString("1-###-###-####");
    string telephoneNum2 = long.Parse(ApplicationInstance.Application["FremontTemplePhone2"].ToString()).ToString("1-###-###-####");
    string telephoneNum6 = long.Parse(ApplicationInstance.Application["FremontTemplePhone1"].ToString()).ToString("(###) ###-####");
    string telephoneNum7 = long.Parse(ApplicationInstance.Application["FremontTemplePhone2"].ToString()).ToString("(###) ###-####");
    string addressLine1 = ApplicationInstance.Application["FremontTempleAddressLine1"].ToString();
    string cityName = ApplicationInstance.Application["FremontTempleCityName"].ToString();
    string stateAbbrev = ApplicationInstance.Application["FremontTempleStateAbbrev"].ToString();
    string zipCode = ApplicationInstance.Application["FremontTempleZipCode"].ToString();
    string webUrl1 = ApplicationInstance.Application["FremontTempleWebUrl1"].ToString();
    string webUrl2 = ApplicationInstance.Application["FremontTempleWebUrl2"].ToString();
    string emailAddress1 = ApplicationInstance.Application["FremontTempleEmailAddress1"].ToString();
    string facebookUrl = ApplicationInstance.Application["FremontTempleFacebookUrl"].ToString();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@templeFullName</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css0")
    @Scripts.Render("~/bundles/scripts0")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Patua+One|Open+Sans|Lato|Roboto" />

    @RenderSection("scripts", required: false)
</head>
<body style="margin: 0px;">
    <script>
        $(document).ready
            (
            function () {
                window_onload();
            }
            );
        function window_onload() {
            alert("This is appearing from window_onload in Shared/_Layout.cshtml - Please implement window_onload in your cshtml");
        }
        $.ajaxSetup({ cache: false });
    </script>
    <div class="col-md-12" style="margin: 0 auto; text-align: center;">
        <table style="margin: 0 auto;">
            <tr>
                <td style="padding-left: 9px; padding-right: 9px;">
                    <img alt="@templeFullName - @templeName @addressLine1, @cityName, @stateAbbrev @zipCode Ph : @telephoneNum6, @telephoneNum7 @webUrl1 @emailAddress1" class="img-responsive" src="@ApplicationInstance.Application["FremontImagesBaseURL"]/HomePage/SVCCBanner2.jpg" style="height: auto; max-width: 1330px; width: 100%;" title="@templeFullName - @templeName @addressLine1, @cityName, @stateAbbrev @zipCode Ph : @telephoneNum6, @telephoneNum7 @webUrl1 @emailAddress1" />
                </td>
            </tr>
            <tr>
                <td style="padding-left: 9px; padding-right: 9px;">
                    <span style="color: #000000; font-family: Arial; font-size: 14px; font-weight: bold;">@addressLine1, @cityName, @stateAbbrev @zipCode</span>&nbsp;
                    <span style="color: #a54000; font-family: Arial; font-size: 14px; font-weight: bold;">Ph :</span>&nbsp;
                    <span style="color: #0000ff; font-family: Arial; font-size: 14px; font-weight: bold;">@telephoneNum6,</span>&nbsp;
                    <span style="color: #ff0000; font-family: Arial; font-size: 14px; font-weight: bold;">@telephoneNum7</span>&nbsp;
                    &nbsp;<a href="@Url.Action("ContactUs", "SVCCTempleFremont")" style="color: #0000ff; font-family: Arial; font-size: 14px; font-weight: bold; text-decoration: underline;" target="_blank">@emailAddress1</a>
                </td>
            </tr>
        </table>
        @RenderBody()
        <span style="color:#000000; font-family: Arial; font-size: 12px;">
            @templeFullName - @templeName, @addressLine1, @cityName, @stateAbbrev @zipCode Tel: <a href="tel:@telephoneNum1" style="text-decoration: underline;">@telephoneNum6</a> / <a href="tel:@telephoneNum2" style="text-decoration: underline;">@telephoneNum7</a><br />
        </span>
        <a href="@webUrl1" style="color:#0000ff; font-family: Arial; font-size: 12px; text-decoration: underline;">@webUrl1</a>
        <span style="padding-left: 9px;">&nbsp;</span>
        <a href="@webUrl2" style="color:#0000ff; font-family: Arial; font-size: 12px; text-decoration: underline;">@webUrl2</a>
        <span style="padding-left: 9px;">&nbsp;</span>
        <a href="mailto:@emailAddress1" style="color:#0000ff; font-family: Arial; font-size: 12px; text-decoration: underline;">@emailAddress1</a><br />
        <div class="fb-like" data-href="@facebookUrl" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" style="vertical-align: top; zoom: 1; display: inline;"></div>
        <a href="@facebookUrl" target="_blank"><img src="~/Images/Fremont/Facebook.jpg" alt="Find us on Facebook (@templeName)" title="Find us on Facebook (@templeName)" /></a>
        <div id="divFacebook" style="margin-left: auto; margin-right: auto; width: 240px;"></div>
        <span style="color:#000000; font-family: Arial; font-size: 12px;">Copyright &copy; @DateTime.Now.Year @templeFullName - @cityName @stateAbbrev (Non-Profit Organization). All rights reserved</span>
    </div>
    <div>
        @Html.Partial("_LoadingModal")
    </div>
    <script type="text/javascript">
        (
            function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }
                (document, 'script', 'facebook-jssdk')
        );
    </script>
</body>
</html>

SVCCTempleApplicationNew/SVCCTempleWeb/Views/SVCCTempleFremont/_Rasi.cshtml
@model List<SVCCTempleWeb.Models.CalendarDateDataModel>
@{
    int index = 0;
}
<table class="table table-bordered table-condensed table-responsive" style="width: 72%;">
    <tr>
        <th>
            #
        </th>
        <th class="text-left">
            Nakshatra
        </th>
        <th class="text-center" colspan="2">
            Start
        </th>
        <th class="text-center" colspan="2">
            Finish
        </th>
    </tr>
    @foreach (var calendarDateDataModel in Model)
    {
        index++;
        <tr>
            <td class="text-right">
                @index
            </td>
            <td class="text-left">
                @calendarDateDataModel.CodeDataModel.CodeDataDesc0
            </td>
            <td class="text-center">
                @calendarDateDataModel.StartDate
            </td>
            <td class="text-center">
                @calendarDateDataModel.StartTime
            </td>
            <td class="text-center">
                @calendarDateDataModel.FinishDate
            </td>
            <td class="text-center">
                @calendarDateDataModel.FinishTime
            </td>
        </tr>
    }
</table>